# Generated by Django 5.1.1 on 2025-12-29 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Изменено'),
        ),
    ]
