# Generated by Django 5.1.1 on 2026-01-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_updated_at_cartitem_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'default_related_name': 'cart_items', 'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
