# Generated by Django 5.1.1 on 2025-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondcategory',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondcategory',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
