# Generated by Django 5.1.1 on 2025-12-11 09:32

import products.services.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_description_brand_title_collection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.ImageField(blank=True, upload_to=products.services.image_utils.image_path, verbose_name='Путь к картинке'),
        ),
    ]
