# Generated by Django 5.1.1 on 2025-12-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_image_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'products', 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_number',
        ),
        migrations.AddField(
            model_name='brand',
            name='articul',
            field=models.CharField(default=0, max_length=7, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='articul',
            field=models.CharField(default=100000, max_length=7, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='articul',
            field=models.CharField(default=200000, max_length=7, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='articul',
            field=models.CharField(default=300000, max_length=7, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(default=500000, max_length=7, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondcategory',
            name='articul',
            field=models.CharField(default=600000, max_length=7, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_category',
            field=models.ForeignKey(default=601000, on_delete=django.db.models.deletion.CASCADE, to='products.secondcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
