# Generated by Django 5.1.1 on 2025-12-31 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'Доставки',
                'default_related_name': 'deliveries',
            },
        ),
    ]
