# Generated by Django 6.0.1 on 2026-01-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'default_related_name': 'deliveries', 'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
    ]
