# Generated by Django 5.1.1 on 2025-12-31 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_address_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Кол-во')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачен'), ('shipped', 'Отправлено'), ('delivered', 'Доставляется'), ('cancelled', 'Отменен')], default='pending')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('paid_at', models.DateField(default=None, verbose_name='Оплачено')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address', verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'default_related_name': 'orders',
            },
        ),
    ]
