# Generated by Django 5.1.1 on 2025-12-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Оплачено'),
        ),
    ]
