# Generated by Django 6.0.1 on 2026-01-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_related_name': 'orders', 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
