# Generated by Django 5.1.1 on 2025-11-27 18:44

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=71111111111, help_text='Формат: +79991234567', max_length=17, unique=True, validators=[users.validators.validate_phone_number], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
