# Generated by Django 5.1.1 on 2025-12-30 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('postal_code', models.PositiveIntegerField(verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ('адрес',),
                'verbose_name_plural': ('Адреса',),
                'default_related_name': 'adresses',
            },
        ),
    ]
