# Generated by Django 5.1.1 on 2025-12-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresses',
            new_name='Adress',
        ),
    ]
