# Generated by Django 5.1.1 on 2025-12-11 09:44

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_smscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='phone',
            field=models.CharField(max_length=17, validators=[users.validators.validate_phone_number]),
        ),
    ]
