# Generated by Django 5.1.1 on 2025-12-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_adresses_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'default_related_name': 'adresses', 'verbose_name': 'адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
