# Generated by Django 5.1.1 on 2025-12-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_adress_address_alter_address_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
