# Generated by Django 5.1.1 on 2025-12-31 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_id_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'default_related_name': 'addresses', 'verbose_name': 'адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
