# Generated by Django 5.1.1 on 2025-12-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_smscode_phone'),
        ('users', '0007_alter_address_options'),
    ]

    operations = [
    ]
